# -*- coding: utf-8 -*-
"""
Render the report content to Markdown.

The DOCX and PDF in deliverables/ are the documents intended for readers. This
Markdown mirror exists so that changes to the report show up as readable diffs
in version control. It is generated, never edited by hand.

    python3 build_markdown.py report/report_working_draft.md
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import report_content as C
from build_docx import APP_FIG_LABEL, APP_TAB_LABEL


def table_md(spec, label):
    out = ["**%s.** %s" % (label, spec["caption"]), ""]
    out.append("| " + " | ".join(spec["headers"]) + " |")
    out.append("|" + "|".join(["---"] * len(spec["headers"])) + "|")
    for row in spec["rows"]:
        cells = [str(c).replace("|", "\\|") for c in row]
        out.append("| " + " | ".join(cells) + " |")
    out.append("")
    return out


def figure_md(spec, label):
    out = []
    if spec.get("path"):
        out.append("![%s](../%s)" % (label, spec["path"]))
    else:
        out.append("> **%s. Figure required, not yet available.**" % label.upper())
        out.append(">")
        out.append("> %s" % spec["need"])
    out.append("")
    out.append("**%s.** %s" % (label, spec["caption"]))
    out.append("")
    return out


def render(blocks, state, fig_label=None, tab_label=None):
    out = []
    for b in blocks:
        k = b[0]
        if k == "h1":
            state["h1"] += 1
            state["h2"] = 0
            out += ["", "## %d  %s" % (state["h1"], b[1]), ""]
        elif k == "h2":
            state["h2"] += 1
            out += ["", "### %d.%d  %s" % (state["h1"], state["h2"], b[1]), ""]
        elif k == "p":
            out += [b[1], ""]
        elif k == "bul":
            out += ["- %s" % i for i in b[1]] + [""]
        elif k == "num":
            out += ["%d. %s" % (n, i) for n, i in enumerate(b[1], 1)] + [""]
        elif k == "eq":
            tokens = b[1] if isinstance(b[1], list) else [(b[1], "i")]
            expr = "".join(t[0] if t[1] != "sub" else "_" + t[0] for t in tokens)
            out += ["", "> %s  (%s)" % (expr.strip(), b[2]), ""]
        elif k in ("fig", "afig"):
            spec = C.FIGURES.get(b[1]) or C.APPENDIX_FIGURES[b[1]]
            lab = (fig_label(b[1]) if fig_label else None)
            if lab is None:
                state["fig"] += 1
                lab = "Figure %d" % state["fig"]
            out += figure_md(spec, lab)
        elif k == "tab":
            state["tab"] += 1
            out += table_md(C.TABLES[b[1]], "Table %d" % state["tab"])
        elif k == "atab":
            out += table_md(C.APPENDIX_TABLES[b[1]],
                            (tab_label(b[1]) if tab_label else b[1]))
    return out


def main(out_path):
    state = dict(h1=0, h2=0, fig=0, tab=0)
    L = ["# %s" % C.TITLE, "", "*%s*" % C.SUBTITLE, ""]
    L.append("> This file is generated by `tools/report_build/build_markdown.py`.")
    L.append("> Edit `tools/report_build/report_content.py` and rebuild. The documents")
    L.append("> intended for readers are the DOCX and PDF in `deliverables/`.")
    L.append("")
    for field, value in C.TITLE_PAGE:
        L.append("- **%s:** %s" % (field, value))
    L += ["", "## Abstract", "", "*%s*" % C.ABSTRACT, "", C.TITLE_NOTE, ""]

    L += render(C.BODY, state)

    L += ["", "## References", ""]
    for i, r in enumerate(C.REFERENCES, 1):
        L.append("%d. %s" % (i, r))
    L += ["", C.REFERENCES_NOTE, ""]

    for letter, title, blocks in C.APPENDICES:
        L += ["", "## Appendix %s  %s" % (letter, title), ""]
        state["h2"] = 0
        L += render(blocks, state,
                    fig_label=lambda k: APP_FIG_LABEL.get(k),
                    tab_label=lambda k: APP_TAB_LABEL.get(k))

    text = "\n".join(L).rstrip() + "\n"
    with open(out_path, "w") as fh:
        fh.write(text)
    print("wrote %s (%d words)" % (out_path, len(text.split())))


if __name__ == "__main__":
    main(sys.argv[1])
